### ISSUE TITLE
No tools are shown in the prompt if there is only one entry in the .tool-versions

### ISSUE THREAD

**Issue by khustochka** [CurryEleison/zsh-asdf-prompt#3]
Thank you for that library!

I have noticed an issue. If there is only one entry in the `.tool-versions`, the prompt is shown as `{}`. If I add a second one, the prompt lists both properly.

```
{} ~/quails | main
$ cat .tool-versions 
ruby 3.1.2

{} ~/quails | main
$ asdf_prompt_info
{} 

{} ~/quails | main
$ echo "elixir  1.13.4" >> .tool-versions

{elixir: 1.13.4, ruby: 3.1.2} ~/quails | main
$ asdf_prompt_info                       
{elixir: 1.13.4, ruby: 3.1.2} 
```

**Comment by CurryEleison** [comment]
That looks wrong. Thanks for the detailed report! I'll take a look, but may be a couple of days before I have an update.

**Comment by CurryEleison** [comment]
@khustochka , I'm having some issues reproducing what you report. Could you assist me by
- Showing the output of `asdf current` as seen when executed in the `~/quails` directory
- Optionally, letting me know if you are on a GNU (i.e. Linux) or POSIX (i.e. macOS) tool chain?
- Also optionally, letting me know what you have in the environment variables 
  - `$ZSH_THEME_ASDF_PROMPT_VERSION_RESOLUTION`, 
  - `$ZSH_THEME_ASDF_PROMPT_PREFIX`, 
  - `$ZSH_THEME_ASDF_PROMPT_POSTFIX`, 
  - `$ZSH_THEME_ASDF_PROMPT_FILTER` and 
  - `$ZSH_THEME_ASDF_PROMPT_VERSION_DETAIL`

Thanks in advance for your patience.

**Comment by khustochka** [comment]
I am using MacOS, and this may be the root cause of the issue. The elimination of the meaningful text happens here in `sed` command: https://github.com/CurryEleison/zsh-asdf-prompt/blob/main/zsh-asdf-prompt.plugin.zsh#L51

If I replace it with `gsed` (GNU sed) it works:

````
$ echo $'ruby\t3.1\t' | awk '{ print $1 ": " $2 $3 }' - | sed -e :a -e N -e '$!ba' -e 's/\n/, /g'

$ echo $'ruby\t3.1\t' | awk '{ print $1 ": " $2 $3 }' - | gsed -e :a -e N -e '$!ba' -e 's/\n/, /g'
ruby: 3.1
````

But for multiple entries sed works just fine:

````
$ echo $'elixir\t1.13.4\t\nerlang\t24.3.4.2\t\nnodejs\tlts\t\nruby\t3.1.2\t' | awk '{ print $1 ": " $2 $3 }' - | sed -e :a -e N -e '$!ba' -e 's/\n/, /g'
elixir: 1.13.4, erlang: 24.3.4.2, nodejs: lts, ruby: 3.1.2
````

**Comment by CurryEleison** [comment]
Awesome report. I have an old mac sitting around somewhere and will see if I can find the right `sed` magic with it

**Comment by CurryEleison** [comment]
Finally found the mac and got the issue sorted, and it will now work on a with vanilla macOS tooling. Thanks for the report!
